### ISSUE TITLE
Unclear description

### ISSUE THREAD

**Issue by vpit** [xsawyerx/perl-critic-policy-valuesandexpressions-prohibitsingleargarrayslice#1]
Hello,

In the description of this module, it is written that

`# List context, single value retrived - the size of the array!`
`# Perl will warn you, but only in runtime`
`my $value     = @array[$index];            # not ok`

This assignment actually holds in scalar context, not in list context. Then `@array[$index]` is a list, evaluated in scalar context, which therefore yields its last element - in this case `$array[$index]` - and not the size of the array or the array slice. Note that this behaviour is consistent with the possibly-variable-length-array-slice `@array[@indices]` where `@indices` only contains one element.

Vincent

**Comment by xsawyerx** [comment]
Eek! You're right, Vincent. Thank you for the correction. I wrote that part in haste. I'll fix it and release in a bit.

**Comment by xsawyerx** [comment]
Resolved in 0.003, released just now. Thanks!
